name: Epics-React library CI/CD

on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install 🔧
        run: yarn install

      - name: Test 🚨
        run: yarn test

      - name: Build 🏗️
        run: yarn run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn run build
      - run: |
          echo lnls-sirius:https://npm.pkg.github.com/lnls-sirius/ > ./.npmrc
          echo '//npm.pkg.github.com/lnls-sirius/:_authToken=${NPM_TOKEN}' >> ./.npmrc
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.EPICS_REACT }}
